#!/bin/bash

# PCN API Testing Script
# Note: This requires authentication via Clerk
# Best to test in browser DevTools for auth

echo "========================================="
echo "PCN API Testing Script"
echo "========================================="
echo ""
echo "⚠️  WARNING: These endpoints require authentication"
echo "Recommended: Use browser DevTools Console instead"
echo ""
echo "To test in browser:"
echo "1. Open http://localhost:3000"
echo "2. Sign in"
echo "3. Open DevTools (F12) → Console tab"
echo "4. Run these commands:"
echo ""
echo "----------------------------------------"
echo "Test 1: Get Pending PCNs"
echo "----------------------------------------"
echo ""
echo "fetch('/api/appointments/pending-pcns')"
echo "  .then(res => res.json())"
echo "  .then(data => console.log(JSON.stringify(data, null, 2)))"
echo ""
echo "----------------------------------------"
echo "Test 2: Get Specific Appointment"
echo "----------------------------------------"
echo ""
echo "fetch('/api/appointments/YOUR_APPOINTMENT_ID')"
echo "  .then(res => res.json())"
echo "  .then(data => console.log(JSON.stringify(data, null, 2)))"
echo ""
echo "----------------------------------------"
echo "Test 3: Submit PCN (Signed)"
echo "----------------------------------------"
echo ""
echo "fetch('/api/appointments/YOUR_APPOINTMENT_ID/submit-pcn', {"
echo "  method: 'POST',"
echo "  headers: { 'Content-Type': 'application/json' },"
echo "  body: JSON.stringify({"
echo "    callOutcome: 'signed',"
echo "    signedNotes: 'Great call!',"
echo "    cashCollected: 5000"
echo "  })"
echo "})"
echo "  .then(res => res.json())"
echo "  .then(data => console.log(JSON.stringify(data, null, 2)))"
echo ""
echo "----------------------------------------"
echo "Test 4: Submit PCN (Showed - With Offer)"
echo "----------------------------------------"
echo ""
echo "fetch('/api/appointments/YOUR_APPOINTMENT_ID/submit-pcn', {"
echo "  method: 'POST',"
echo "  headers: { 'Content-Type': 'application/json' },"
echo "  body: JSON.stringify({"
echo "    callOutcome: 'showed',"
echo "    firstCallOrFollowUp: 'first_call',"
echo "    wasOfferMade: true,"
echo "    whyDidntMoveForward: 'Price objection',"
echo "    followUpScheduled: true,"
echo "    followUpDate: '2025-11-01T14:00:00.000Z',"
echo "    nurtureType: 'thinking_it_over',"
echo "    notes: 'Will call back Friday'"
echo "  })"
echo "})"
echo "  .then(res => res.json())"
echo "  .then(data => console.log(JSON.stringify(data, null, 2)))"
echo ""
echo "========================================="
echo ""
echo "Checking server status..."

# Check if server is running
if curl -s http://localhost:3000 > /dev/null; then
    echo "✅ Server is running on http://localhost:3000"
else
    echo "❌ Server is not responding on http://localhost:3000"
    echo "Run: npm run dev"
fi

echo ""

